"""production_phase1

Revision ID: 1a1ca842d35f
Revises: 32ff72944847
Create Date: 2026-05-25 05:30:22.652798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1ca842d35f'
down_revision: Union[str, Sequence[str], None] = '32ff72944847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('machine_code', sa.Text(), nullable=False),
    sa.Column('machine_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Commissioning', 'Active', 'Maintenance', 'Decommissioned', 'Deleted', name='machinestatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_machines_deleted_fields_consistency'),
    sa.CheckConstraint("machine_code ~ '^MFUK_M[0-9]{2}$'", name='ck_machines_machine_code_format'),
    sa.CheckConstraint('length(btrim(machine_code)) > 0 AND length(btrim(machine_name)) > 0', name='ck_machines_important_fields_not_blank'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_machines_machine_code_not_deleted', 'machines', ['machine_code'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_table('skus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('sku_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Active', 'Inactive', 'Obsolete', 'Deleted', name='skustatus'), nullable=False),
    sa.Column('thumbnail_placeholder', sa.Text(), nullable=True),
    sa.Column('thumbnail_bucket', sa.Text(), nullable=True),
    sa.Column('thumbnail_object_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_byte_size', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_content_type', sa.Text(), nullable=True),
    sa.Column('thumbnail_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_skus_deleted_fields_consistency'),
    sa.CheckConstraint("sku_code ~ '^[A-Z0-9_]{3,80}$'", name='ck_skus_sku_code_format'),
    sa.CheckConstraint('length(btrim(sku_code)) > 0 AND length(btrim(sku_name)) > 0', name='ck_skus_important_fields_not_blank'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_skus_sku_code_not_deleted', 'skus', ['sku_code'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_table('recipes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('machine_id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_code', sa.Text(), nullable=False),
    sa.Column('recipe_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Obsolete', 'Deleted', name='recipestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_recipes_deleted_fields_consistency'),
    sa.CheckConstraint("recipe_code ~ '^[A-Z0-9._-]{3,80}$'", name='ck_recipes_recipe_code_format'),
    sa.CheckConstraint('length(btrim(recipe_code)) > 0 AND length(btrim(recipe_name)) > 0', name='ck_recipes_important_fields_not_blank'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_recipes_recipe_code_not_deleted', 'recipes', ['recipe_code'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_index('uq_recipes_sku_machine_not_deleted', 'recipes', ['sku_id', 'machine_id'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_table('recipe_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.Text(), nullable=False),
    sa.Column('version_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'UnderReview', 'Approved', 'Released', 'Superseded', 'Archived', 'Obsolete', 'Deleted', name='recipeversionstatus'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('engineering_reason', sa.Text(), nullable=True),
    sa.Column('source_version_id', sa.BigInteger(), nullable=True),
    sa.Column('superseded_by_version_id', sa.BigInteger(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.BigInteger(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_id', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_recipe_versions_deleted_fields_consistency'),
    sa.CheckConstraint("version_code ~ '^[A-Z0-9._-]{3,80}$'", name='ck_recipe_versions_version_code_format'),
    sa.CheckConstraint('length(btrim(version_code)) > 0 AND length(btrim(version_name)) > 0', name='ck_recipe_versions_important_fields_not_blank'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['archived_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['recipe_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_version_id'], ['recipe_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_recipe_versions_one_released_per_recipe', 'recipe_versions', ['recipe_id'], unique=True, postgresql_where=sa.text("status = 'Released'"))
    op.create_index('uq_recipe_versions_recipe_version_no_not_deleted', 'recipe_versions', ['recipe_id', 'version_no'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_index('uq_recipe_versions_version_code_not_deleted', 'recipe_versions', ['version_code'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_recipe_versions_version_code_not_deleted', table_name='recipe_versions', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_index('uq_recipe_versions_recipe_version_no_not_deleted', table_name='recipe_versions', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_index('uq_recipe_versions_one_released_per_recipe', table_name='recipe_versions', postgresql_where=sa.text("status = 'Released'"))
    op.drop_table('recipe_versions')
    op.drop_index('uq_recipes_sku_machine_not_deleted', table_name='recipes', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_index('uq_recipes_recipe_code_not_deleted', table_name='recipes', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_table('recipes')
    op.drop_index('uq_skus_sku_code_not_deleted', table_name='skus', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_table('skus')
    op.drop_index('uq_machines_machine_code_not_deleted', table_name='machines', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_table('machines')
    # ### end Alembic commands ###
