"""rbac_phase1

Revision ID: 32ff72944847
Revises: 537fa347cd4b
Create Date: 2026-05-05 04:47:57.864929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ff72944847'
down_revision: Union[str, Sequence[str], None] = '537fa347cd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permission_code', sa.Text(), nullable=False),
    sa.Column('permission_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('view', 'create', 'update', 'delete', 'approve', 'export', 'assign', 'revoke', 'execute', 'override', name='permissioncategory'), nullable=False),
    sa.Column('is_system_permission', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Deprecated', name='permissionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_permissions_deleted_fields_consistency'),
    sa.CheckConstraint("permission_code ~ '^[A-Z0-9_]{3,80}$'", name='ck_permissions_permission_code_format'),
    sa.CheckConstraint('length(btrim(permission_code)) > 0 AND length(btrim(permission_name)) > 0 AND length(btrim(module)) > 0', name='ck_permissions_important_fields_not_blank'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_permissions_permission_code_not_deleted', 'permissions', ['permission_code'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.Text(), nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Suspended', name='rolestatus'), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_roles_deleted_fields_consistency'),
    sa.CheckConstraint('length(btrim(role_code)) > 0 AND length(btrim(role_name)) > 0', name='ck_roles_important_fields_not_blank'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_roles_role_code_not_deleted', 'roles', ['role_code'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Suspended', name='rolepermissionstatus'), nullable=False),
    sa.Column('effect', sa.Enum('Allow', 'Deny', name='rolepermissioneffect'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_role_permissions_deleted_fields_consistency'),
    sa.CheckConstraint('priority >= 0', name='ck_role_permissions_priority_not_negative'),
    sa.CheckConstraint('valid_from IS NULL OR valid_until IS NULL OR valid_from < valid_until', name='ck_role_permissions_valid_dates_consistency'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_role_permissions_effective', 'role_permissions', ['role_id', 'permission_id', 'priority'], unique=True, postgresql_where=sa.text("status = 'Active' "))
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Suspended', 'Revoked', name='userrolestatus'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('revoked_by_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_user_roles_deleted_fields_consistency'),
    sa.CheckConstraint("((status = 'Revoked' AND revoked_at IS NOT NULL AND revoked_by_id IS NOT NULL) OR (status <> 'Revoked' AND revoked_at IS NULL AND revoked_by_id IS NULL))", name='ck_user_roles_revoked_fields_consistency'),
    sa.CheckConstraint('valid_from IS NULL OR valid_until IS NULL OR valid_from < valid_until', name='ck_user_roles_valid_window'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_roles_effective', 'user_roles', ['user_id', 'role_id'], unique=True, postgresql_where=sa.text("status = 'Active' "))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_roles_effective', table_name='user_roles', postgresql_where=sa.text("status = 'Active' "))
    op.drop_table('user_roles')
    op.drop_index('uq_role_permissions_effective', table_name='role_permissions', postgresql_where=sa.text("status = 'Active' "))
    op.drop_table('role_permissions')
    op.drop_index('uq_roles_role_code_not_deleted', table_name='roles', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_table('roles')
    op.drop_index('uq_permissions_permission_code_not_deleted', table_name='permissions', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_table('permissions')
    # ### end Alembic commands ###
