"""repository_image

Revision ID: 485c30d1229f
Revises: 1a1ca842d35f
Create Date: 2026-06-08 08:03:19.670881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '485c30d1229f'
down_revision: Union[str, Sequence[str], None] = '1a1ca842d35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipe_version_id', sa.BigInteger(), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Active', 'Deleted', name='repositoryimagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_repository_images_deleted_fields_consistency'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_repository_images_object_key_not_deleted', 'repository_images', ['bucket', 'object_key'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    op.create_index('uq_repository_images_reference_true_per_recipe_version', 'repository_images', ['recipe_version_id'], unique=True, postgresql_where=sa.text('is_reference = TRUE'))
    op.drop_column('skus', 'thumbnail_content_type')
    op.drop_column('skus', 'thumbnail_updated_at')
    op.drop_column('skus', 'thumbnail_byte_size')
    op.drop_column('skus', 'thumbnail_bucket')
    op.drop_column('skus', 'thumbnail_object_key')
    op.drop_column('skus', 'thumbnail_placeholder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('thumbnail_placeholder', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skus', sa.Column('thumbnail_object_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skus', sa.Column('thumbnail_bucket', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skus', sa.Column('thumbnail_byte_size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('skus', sa.Column('thumbnail_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('skus', sa.Column('thumbnail_content_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('uq_repository_images_reference_true_per_recipe_version', table_name='repository_images', postgresql_where=sa.text('is_reference = TRUE'))
    op.drop_index('uq_repository_images_object_key_not_deleted', table_name='repository_images', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_table('repository_images')
    # ### end Alembic commands ###
