"""init

Revision ID: 537fa347cd4b
Revises: 
Create Date: 2026-04-24 06:42:48.055689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537fa347cd4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_code', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Enum('Human', 'System', 'Service', 'Robot', 'PLC', name='usertype'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Suspended', 'Deleted', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("((status = 'Deleted' AND deleted_at IS NOT NULL AND deleted_by_id IS NOT NULL) OR (status <> 'Deleted' AND deleted_at IS NULL AND deleted_by_id IS NULL))", name='ck_users_deleted_fields_consistency'),
    sa.CheckConstraint("(password_hash IS NULL) OR (status <> 'Deleted' AND user_type IN ('Human'))", name='ck_users_password_auth_consistency'),
    sa.CheckConstraint('length(btrim(full_name)) > 0', name='ck_users_full_name_not_blank'),
    sa.CheckConstraint('length(btrim(user_code)) > 0', name='ck_users_user_code_not_blank'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_user_code_not_deleted', 'users', ['user_code'], unique=True, postgresql_where=sa.text("status <> 'Deleted'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_user_code_not_deleted', table_name='users', postgresql_where=sa.text("status <> 'Deleted'"))
    op.drop_table('users')
    # ### end Alembic commands ###
